### ISSUE TITLE
CI/CD for github

### ISSUE THREAD

**Issue by oarcher** [umr-lops/xsar#7]
Goal is to provide CI/CD with github actions.

It should include osx and windows.

**Comment by alevieux** [comment]
First pull request #6 for init the CI/CD

**Comment by alevieux** [comment]
GitHub Action workflow [Dashbord](https://github.com/umr-lops/xsar/actions)

MacOS no python 3.6 the workflow was stay stuck
MacOS with python 3.7 and 3.8:  bug with libtiledb.dylib Reason: image not found

Windows with python 3.6:  bug with rasterio AttributeError: rms

Add more information of package in workflows

**Comment by alevieux** [comment]
For Windows the Rasterio version (Rasterio 1.1.0) is old for using rms (Rasterio 1.2.6)

For MacOS with python 3.8 the problem was fix when add package **tbb** in conda install but same problem of Windows with Rasterio version

For MacOS with python 3.7 the problem was fix when add package **tbb** but another problem appears with poppler:
`ImportError: dlopen(/usr/local/miniconda/envs/xsar/lib/python3.7/site-packages/rasterio/_base.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libpoppler.91.dylib
  Referenced from: /usr/local/miniconda/envs/xsar/lib/libgdal.26.dylib
  Reason: image not found` 
When you add package poppler in conda install the problem was same

**Comment by oarcher** [comment]
So I propose:
  * add tbb dep
  * use 'average' instead of 'rms' for tests (so old version of rasterio will works)

**Comment by alevieux** [comment]
MacOS and Ubuntu can forcing Rasterio 1.2.6 for using resampling rms, because in python 3.7 conda by default not installed the higher version of Rasterio.
Conda install for Mac: `conda install -c conda-forge rasterio">=1.2.6" gdal cartopy dask[array] tbb`
Conda install for Ubuntu: `conda install -c conda-forge rasterio">=1.2.6" gdal cartopy dask[array]`

Windows with python 3.6 conda-forge have maximum for Rasterio is 1.1.0, no rms for this configuration
Conda install for Windows: `conda install -c conda-forge rasterio gdal cartopy dask[array] fiona`

I will update the doc with new installation for any OS

**Comment by alevieux** [comment]
Code update with the pull request #9

**Comment by oarcher** [comment]
Everything is working as expected, [github action dashboard](https://github.com/umr-lops/xsar/actions) looks good.
GDAL 3.3 test will be automatically fixed when available.
Some platforms and python version has some specificity that were handled by the tests.

Nice job @alevieux !
